### ISSUE TITLE
[REQUEST] Create "User" model

### ISSUE THREAD

**Issue by AldoTu** [AldoTu/hf-ionic-app-backend#1]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The current project has no models.

**Expected behavior:**
The project should have at least one "User" model inside a models folder.

**Other information:**
The PR should have at least 1 "User" model inside a "models" folder and the User model being used inside the app.js file in the root

**Comment by Bootspace** [comment]
I want to work on this.

**Comment by AldoTu** [comment]
Done @Bootspace!!

**Comment by AldoTu** [comment]
Grat @Bootspace ! Please feel free to contribute more or get inside our discord server :)
